# Generated by Django 5.2.13 on 2026-04-07 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(choices=[('usd', 'US Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('cad', 'Canadian Dollar'), ('aud', 'Australian Dollar'), ('jpy', 'Japanese Yen'), ('inr', 'Indian Rupee'), ('brl', 'Brazilian Real')], default='usd', max_length=3)),
                ('tax_id', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'billing customer',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_method_id', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('card_brand', models.CharField(blank=True, default='', max_length=20)),
                ('card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='billing.billingcustomer')),
            ],
            options={
                'verbose_name': 'payment method',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'trialing'), ('active', 'active'), ('past_due', 'past_due'), ('canceled', 'canceled'), ('unpaid', 'unpaid'), ('incomplete', 'incomplete')], default='active', max_length=20)),
                ('interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], default='monthly', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing.billingcustomer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan')),
            ],
            options={
                'verbose_name': 'subscription',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('amount_remaining', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('usd', 'US Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('cad', 'Canadian Dollar'), ('aud', 'Australian Dollar'), ('jpy', 'Japanese Yen'), ('inr', 'Indian Rupee'), ('brl', 'Brazilian Real')], default='usd', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('refunded', 'refunded'), ('canceled', 'canceled')], default='pending', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('invoice_pdf_url', models.URLField(blank=True, default='')),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.billingcustomer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'invoice',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_slug', models.SlugField(help_text='Which metered feature this usage is for')),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'usage record',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['subscription', 'feature_slug', 'timestamp'], name='billing_usa_subscri_56bc29_idx')],
            },
        ),
    ]
