# Generated by Django 5.2.13 on 2026-04-07 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the tenant / organization.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier, also used as subdomain.', max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, db_index=True, default='', help_text='Optional custom domain mapped to this tenant.', max_length=255)),
                ('schema_name', models.CharField(blank=True, default='', help_text='PostgreSQL schema name (schema-per-tenant mode only).', max_length=63)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Arbitrary tenant-level configuration (feature flags, branding, limits, etc.).')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Setup')], db_index=True, default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='member', help_text='Role within this tenant (e.g. owner, admin, member).', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text="If True this is the user's default tenant.")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tenant membership',
                'verbose_name_plural': 'tenant memberships',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_user')],
            },
        ),
    ]
