# Generated by Django 5.2.13 on 2026-04-07 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('usd', 'US Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('cad', 'Canadian Dollar'), ('aud', 'Australian Dollar'), ('jpy', 'Japanese Yen'), ('inr', 'Indian Rupee'), ('brl', 'Brazilian Real')], default='usd', max_length=3)),
                ('stripe_monthly_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_yearly_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('max_members', models.IntegerField(default=1, help_text='Max team members. 0 = unlimited.')),
                ('max_storage_mb', models.IntegerField(default=100, help_text='Max storage in MB. 0 = unlimited.')),
                ('max_api_calls_per_month', models.IntegerField(default=1000, help_text='0 = unlimited.')),
                ('is_public', models.BooleanField(default=True, help_text='Show on pricing page')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight on pricing page')),
                ('trial_days', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price_monthly'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFeatureDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['category', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, default='')),
                ('is_boolean', models.BooleanField(default=True, help_text='True = on/off feature, False = metered/limited')),
                ('limit_value', models.IntegerField(blank=True, help_text='Numeric limit for metered features', null=True)),
                ('limit_unit', models.CharField(blank=True, default='', help_text="e.g., 'requests', 'GB', 'users'", max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='plans.plan')),
            ],
            options={
                'ordering': ['plan', 'name'],
                'abstract': False,
                'unique_together': {('plan', 'slug')},
            },
        ),
    ]
