# Generated by Django 5.2.13 on 2026-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planfeature',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'slug'), name='unique_plan_feature_slug'),
        ),
    ]
